name: 分类

on:
  workflow_dispatch:
  push:
    paths:
      - '.history/**'

jobs:
  sort:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run Sort Script
        run: python3 ./.github/scripts/src_sort.py

      - name: Run Merge Script
        run: python3 ./.github/scripts/src_merge.py

      - name: Push
        run: |
          git config user.email "github-actions@github.com"
          git config user.name "Robot"
          git add .
          git commit -m "update" -a
          git push origin main
